import Exercicio from "../screens/Exercicio";

export function getExercicios(){
  return[
    {
      id: 1,
      feito: false,
      acertou: false,
      pergunta: "Qual é o valor de b na função y = 3x + 5?",
      imagem: "",
      tipo: "múltipla escolha",
      nivel_dificuldade: "facil",
      respostas: [
        { id: "a", texto: "5", correta: true },
        { id: "b", texto: "6", correta: false },
        { id: "c", texto: "4", correta: false },
        { id: "d", texto: "7", correta: false },
      ],
    },
    {
      id: 2,
      feito: false,
      acertou: false,
      pergunta: "Qual é o ponto de interseção da função y = x - 5 com o eixo y?",
      imagem: "",
      tipo: "múltipla escolha",
      nivel_dificuldade: "facil",
      respostas: [
        { id: "a", texto: "-5", correta: true },
        { id: "b", texto: "-1", correta: false },
        { id: "c", texto: "0", correta: false },
        { id: "d", texto: "5", correta: false },
      ],
    },
    {
      id: 3,
      feito: false,
      acertou: false,
      pergunta: "Qual é o valor de a na função f(x) = 3x + 5?",
      tipo: "múltipla escolha",
      nivel_dificuldade: "fácil",
      respostas: [
        { id: "a", texto: "3", correta: true },
        { id: "b", texto: "5", correta: false },
        { id: "c", texto: "8", correta: false },
        { id: "d", texto: "1", correta: false },
      ],
    },
    {
      id: 4,
      feito: false,
      acertou: false,
      pergunta: "Qual é o valor de b na função y = -2x + 4?",
      imagem: "",
      tipo: "múltipla escolha",
      nivel_dificuldade: "facil",
      respostas: [
        { id: "a", texto: "3", correta:  false},
        { id: "b", texto: "5", correta: false },
        { id: "c", texto: "4", correta: true },
        { id: "d", texto: "2", correta: false },
      ],
    },
    {
      id: 5,
      feito: false,
      acertou: false,
      pergunta: "Para qual valor de x temos y = 0 na função y = 4x + 8?",
      imagem: "",
      tipo: "múltipla escolha",
      nivel_dificuldade: "facil",
      respostas: [
        { id: "a", texto: "-2", correta: true },
        { id: "b", texto: "-4", correta: false },
        { id: "c", texto: "2", correta: false },
        { id: "d", texto: "4", correta: false },
      ],
    },
    {
      id: 6,
      feito: false,
      acertou: false,
      pergunta: "Qual é o valor de a na função f(x) = -2x + 4?",
      tipo: "múltipla escolha",
      nivel_dificuldade: "fácil",
      respostas: [
        { id: "a", texto: "-2", correta: true },
        { id: "b", texto: "4", correta: false },
        { id: "c", texto: "-4", correta: false },
        { id: "d", texto: "2", correta: false },
      ],
    },
    {
      id: 7,
      feito: false,
      acertou: false,
      pergunta: "Qual é o valor de b na função y = 1x + -6?",
      imagem: "",
      tipo: "múltipla escolha",
      nivel_dificuldade: "facil",
      respostas: [
        { id: "a", texto: "-7", correta: false },
        { id: "b", texto: "-5", correta: false },
        { id: "c", texto: "-6", correta: true  },
        { id: "d", texto: "-8", correta: false },
      ],
    },
    {
      id: 8,
      feito: false,
      acertou: false,
      pergunta: "Qual é o valor de x para y = 10 na função y = 2x + 6?",
      imagem: "",
      tipo: "múltipla escolha",
      nivel_dificuldade: "facil",
      respostas: [
        { id: "a", texto: "2", correta: true },
        { id: "b", texto: "1", correta: false },
        { id: "c", texto: "-2", correta: false },
        { id: "d", texto: "3", correta: false },
      ],
    },
    {
      id: 9,
      feito: false,
      acertou: false,
      pergunta: "Qual é o valor de a na função f(x) = 5x - 7?",
      tipo: "múltipla escolha",
      nivel_dificuldade: "fácil",
      respostas: [
        { id: "a", texto: "5", correta: true },
        { id: "b", texto: "-7", correta: false },
        { id: "c", texto: "7", correta: false },
        { id: "d", texto: "-5", correta: false },
      ],
    },
    {
      id: 10,
      feito: false,
      acertou: false,
      pergunta: "Qual é o valor de b na função y = 0x + 7?",
      imagem: "",
      tipo: "múltipla escolha",
      nivel_dificuldade: "facil",
      respostas: [
        { id: "a", texto: "7", correta: true },
        { id: "b", texto: "8", correta: false },
        { id: "c", texto: "6", correta: false },
        { id: "d", texto: "9", correta: false },
      ],
    },
    {
      id: 11,
      feito: false,
      acertou: false,
      pergunta: "Qual é o coeficiente angular (a) na função y = 5x - 3?",
      imagem: "",
      tipo: "múltipla escolha",
      nivel_dificuldade: "facil",
      respostas: [
        { id: "a", texto: "5", correta: true },
        { id: "b", texto: "-5", correta: false },
        { id: "c", texto: "-3", correta: false },
        { id: "d", texto: "3", correta: false },
      ],
    },
    {
      id: 12,
      feito: false,
      acertou: false,
      pergunta: "Qual é o valor de a na função f(x) = x - 6?",
      tipo: "múltipla escolha",
      nivel_dificuldade: "fácil",
      respostas: [
        { id: "a", texto: "1", correta: true },
        { id: "b", texto: "-6", correta: false },
        { id: "c", texto: "0", correta: false },
        { id: "d", texto: "-1", correta: false },
      ],
    },
    {
      id: 13,
      feito: false,
      acertou: false,
      pergunta: "Qual é o valor de b na função y = 4x + -3?",
      imagem: "",
      tipo: "múltipla escolha",
      nivel_dificuldade: "facil",
      respostas: [
        { id: "a", texto: "-3", correta: true },
        { id: "b", texto: "-4", correta: false },
        { id: "c", texto: "-2", correta: false },
        { id: "d", texto: "-1", correta: false },
      ],
    },
    {
      id: 14,
      feito: false,
      acertou: false,
      pergunta: "Qual é o valor de y quando x = 0 na função y = -4x + 1?",
      imagem: "",
      tipo: "múltipla escolha",
      nivel_dificuldade: "facil",
      respostas: [
        { id: "a", texto: "0", correta: false },
        { id: "b", texto: "-4", correta: false },
        { id: "c", texto: "-1", correta: false },
        { id: "d", texto: "1", correta: true },
      ],
    },
    {
      id: 15,
      feito: false,
      acertou: false,
      pergunta: "Qual é o valor de a na função f(x) = -4x + 10?",
      tipo: "múltipla escolha",
      nivel_dificuldade: "fácil",
      respostas: [
        { id: "a", texto: "-4", correta: true },
        { id: "b", texto: "4", correta: false },
        { id: "c", texto: "10", correta: false },
        { id: "d", texto: "-10", correta: false },
      ],
    },

  ];
}


export function getExerciciosFacil(){
  return[
    {
      id: 1,
      feito: false,
      acertou: false,
      pergunta: "Qual é o valor de b na função y = 3x + 5?",
      imagem: "",
      tipo: "múltipla escolha",
      nivel_dificuldade: "facil",
      respostas: [
        { id: "a", texto: "5", correta: true },
        { id: "b", texto: "6", correta: false },
        { id: "c", texto: "4", correta: false },
        { id: "d", texto: "7", correta: false },
      ],
    },
    {
      id: 2,
      feito: false,
      acertou: false,
      pergunta: "Qual é o ponto de interseção da função y = x - 5 com o eixo y?",
      imagem: "",
      tipo: "múltipla escolha",
      nivel_dificuldade: "facil",
      respostas: [
        { id: "a", texto: "-5", correta: true },
        { id: "b", texto: "-1", correta: false },
        { id: "c", texto: "0", correta: false },
        { id: "d", texto: "5", correta: false },
      ],
    },
    {
      id: 3,
      feito: false,
      acertou: false,
      pergunta: "Qual é o valor de a na função f(x) = 3x + 5?",
      tipo: "múltipla escolha",
      nivel_dificuldade: "fácil",
      respostas: [
        { id: "a", texto: "3", correta: true },
        { id: "b", texto: "5", correta: false },
        { id: "c", texto: "8", correta: false },
        { id: "d", texto: "1", correta: false },
      ],
    },
    {
      id: 4,
      feito: false,
      acertou: false,
      pergunta: "Qual é o valor de b na função y = -2x + 4?",
      imagem: "",
      tipo: "múltipla escolha",
      nivel_dificuldade: "facil",
      respostas: [
        { id: "a", texto: "3", correta:  false},
        { id: "b", texto: "5", correta: false },
        { id: "c", texto: "4", correta: true },
        { id: "d", texto: "2", correta: false },
      ],
    },
    {
      id: 5,
      feito: false,
      acertou: false,
      pergunta: "Para qual valor de x temos y = 0 na função y = 4x + 8?",
      imagem: "",
      tipo: "múltipla escolha",
      nivel_dificuldade: "facil",
      respostas: [
        { id: "a", texto: "-2", correta: true },
        { id: "b", texto: "-4", correta: false },
        { id: "c", texto: "2", correta: false },
        { id: "d", texto: "4", correta: false },
      ],
    },
    {
      id: 6,
      feito: false,
      acertou: false,
      pergunta: "Qual é o valor de a na função f(x) = -2x + 4?",
      tipo: "múltipla escolha",
      nivel_dificuldade: "fácil",
      respostas: [
        { id: "a", texto: "-2", correta: true },
        { id: "b", texto: "4", correta: false },
        { id: "c", texto: "-4", correta: false },
        { id: "d", texto: "2", correta: false },
      ],
    },
    {
      id: 7,
      feito: false,
      acertou: false,
      pergunta: "Qual é o valor de b na função y = 1x + -6?",
      imagem: "",
      tipo: "múltipla escolha",
      nivel_dificuldade: "facil",
      respostas: [
        { id: "a", texto: "-7", correta: false },
        { id: "b", texto: "-5", correta: false },
        { id: "c", texto: "-6", correta: true  },
        { id: "d", texto: "-8", correta: false },
      ],
    },
    {
      id: 8,
      feito: false,
      acertou: false,
      pergunta: "Qual é o valor de x para y = 10 na função y = 2x + 6?",
      imagem: "",
      tipo: "múltipla escolha",
      nivel_dificuldade: "facil",
      respostas: [
        { id: "a", texto: "2", correta: true },
        { id: "b", texto: "1", correta: false },
        { id: "c", texto: "-2", correta: false },
        { id: "d", texto: "3", correta: false },
      ],
    },
    {
      id: 9,
      feito: false,
      acertou: false,
      pergunta: "Qual é o valor de a na função f(x) = 5x - 7?",
      tipo: "múltipla escolha",
      nivel_dificuldade: "fácil",
      respostas: [
        { id: "a", texto: "5", correta: true },
        { id: "b", texto: "-7", correta: false },
        { id: "c", texto: "7", correta: false },
        { id: "d", texto: "-5", correta: false },
      ],
    },
    {
      id: 10,
      feito: false,
      acertou: false,
      pergunta: "Qual é o valor de b na função y = 0x + 7?",
      imagem: "",
      tipo: "múltipla escolha",
      nivel_dificuldade: "facil",
      respostas: [
        { id: "a", texto: "7", correta: true },
        { id: "b", texto: "8", correta: false },
        { id: "c", texto: "6", correta: false },
        { id: "d", texto: "9", correta: false },
      ],
    },
    {
      id: 11,
      feito: false,
      acertou: false,
      pergunta: "Qual é o coeficiente angular (a) na função y = 5x - 3?",
      imagem: "",
      tipo: "múltipla escolha",
      nivel_dificuldade: "facil",
      respostas: [
        { id: "a", texto: "5", correta: true },
        { id: "b", texto: "-5", correta: false },
        { id: "c", texto: "-3", correta: false },
        { id: "d", texto: "3", correta: false },
      ],
    },
    {
      id: 12,
      feito: false,
      acertou: false,
      pergunta: "Qual é o valor de a na função f(x) = x - 6?",
      tipo: "múltipla escolha",
      nivel_dificuldade: "fácil",
      respostas: [
        { id: "a", texto: "1", correta: true },
        { id: "b", texto: "-6", correta: false },
        { id: "c", texto: "0", correta: false },
        { id: "d", texto: "-1", correta: false },
      ],
    },
    {
      id: 13,
      feito: false,
      acertou: false,
      pergunta: "Qual é o valor de b na função y = 4x + -3?",
      imagem: "",
      tipo: "múltipla escolha",
      nivel_dificuldade: "facil",
      respostas: [
        { id: "a", texto: "-3", correta: true },
        { id: "b", texto: "-4", correta: false },
        { id: "c", texto: "-2", correta: false },
        { id: "d", texto: "-1", correta: false },
      ],
    },
    {
      id: 14,
      feito: false,
      acertou: false,
      pergunta: "Qual é o valor de y quando x = 0 na função y = -4x + 1?",
      imagem: "",
      tipo: "múltipla escolha",
      nivel_dificuldade: "facil",
      respostas: [
        { id: "a", texto: "0", correta: false },
        { id: "b", texto: "-4", correta: false },
        { id: "c", texto: "-1", correta: false },
        { id: "d", texto: "1", correta: true },
      ],
    },
    {
      id: 15,
      feito: false,
      acertou: false,
      pergunta: "Qual é o valor de a na função f(x) = -4x + 10?",
      tipo: "múltipla escolha",
      nivel_dificuldade: "fácil",
      respostas: [
        { id: "a", texto: "-4", correta: true },
        { id: "b", texto: "4", correta: false },
        { id: "c", texto: "10", correta: false },
        { id: "d", texto: "-10", correta: false },
      ],
    },

  ];
}

export function getExerciciosMedio() {
  return [
    {  
      id: 1,
      feito: false,
      acertou: false,
      pergunta: "Classifique o Gráfico a seguir",
      imagem: require("../../assets/um.png"),
      tipo: "múltipla escolha",
      nivel_dificuldade: "médio",
      respostas: [
        { id: "a", texto: "O gráfico é crescente.", correta: true },
        { id: "b", texto: "O gráfico é decrescente.", correta: false },
        { id: "c", texto: "O gráfico é constante.", correta: false },
        { id: "d", texto: "O gráfico é uma parábola.", correta: false },
      ],
    },
    { 
      id: 2,
      feito: false,
      acertou: false,
      pergunta: "Classifique o Gráfico a seguir",
      imagem: require("../../assets/dois.png"),
      tipo: "múltipla escolha",
      nivel_dificuldade: "médio",
      respostas: [
        { id: "a", texto: "O gráfico é crescente.", correta: false },
        { id: "b", texto: "O gráfico é decrescente.", correta: true },
        { id: "c", texto: "O gráfico é constante.", correta: false },
        { id: "d", texto: "O gráfico é uma parábola.", correta: false },
      ],
    },
    { 
      id: 3,
      feito: false,
      acertou: false,
      pergunta: "Classifique o Gráfico a seguir",
      imagem: require("../../assets/3.png"),
      tipo: "múltipla escolha",
      nivel_dificuldade: "médio",
      respostas: [
        { id: "a", texto: "O gráfico é crescente.", correta: true },
        { id: "b", texto: "O gráfico é decrescente.", correta: false },
        { id: "c", texto: "O gráfico é constante.", correta: false },
        { id: "d", texto: "O gráfico é uma parábola.", correta: false },
      ],
    },
    { 
      id: 4,
      feito: false,
      acertou: false,
      pergunta: "Classifique o Gráfico a seguir",
      imagem: require("../../assets/4.png"),
      tipo: "múltipla escolha",
      nivel_dificuldade: "médio",
      respostas: [
        { id: "a", texto: "O gráfico é crescente.", correta: false },
        { id: "b", texto: "O gráfico é decrescente.", correta: false },
        { id: "c", texto: "O gráfico é constante.", correta: false },
        { id: "d", texto: "O gráfico é uma parábola.", correta: false },
      ],
    },
    { 
      id: 5,
      feito: false,
      acertou: false,
      pergunta: "Classifique o Gráfico a seguir",
      imagem: require("../../assets/5.png"),
      tipo: "múltipla escolha",
      nivel_dificuldade: "médio",
      respostas: [
        { id: "a", texto: "O gráfico é crescente.", correta: false },
        { id: "b", texto: "O gráfico é decrescente.", correta: false },
        { id: "c", texto: "O gráfico é constante.", correta: false },
        { id: "d", texto: "O gráfico é uma parábola.", correta: false },
      ],
    },
    { 
      id: 6,
      feito: false,
      acertou: false,
      pergunta: "Classifique o Gráfico a seguir",
      imagem: require("../../assets/6.png"),
      tipo: "múltipla escolha",
      nivel_dificuldade: "médio",
      respostas: [
        { id: "a", texto: "O gráfico é crescente.", correta: false },
        { id: "b", texto: "O gráfico é decrescente.", correta: false },
        { id: "c", texto: "O gráfico é constante.", correta: false },
        { id: "d", texto: "O gráfico é uma parábola.", correta: false },
      ],
    },
    { 
      id: 7,
      feito: false,
      acertou: false,
      pergunta: "Classifique o Gráfico a seguir",
      imagem: require("../../assets/7.png"),
      tipo: "múltipla escolha",
      nivel_dificuldade: "médio",
      respostas: [
        { id: "a", texto: "O gráfico é crescente.", correta: false },
        { id: "b", texto: "O gráfico é decrescente.", correta: false },
        { id: "c", texto: "O gráfico é constante.", correta: false },
        { id: "d", texto: "O gráfico é uma parábola.", correta: false },
      ],
    },
    { 
      id: 8,
      feito: false,
      acertou: false,
      pergunta: "Classifique o Gráfico a seguir",
      imagem: require("../../assets/8.png"),
      tipo: "múltipla escolha",
      nivel_dificuldade: "médio",
      respostas: [
        { id: "a", texto: "O gráfico é crescente.", correta: false },
        { id: "b", texto: "O gráfico é decrescente.", correta: false },
        { id: "c", texto: "O gráfico é constante.", correta: false },
        { id: "d", texto: "O gráfico é uma parábola.", correta: false },
      ],
    },
    { 
      id: 9,
      feito: false,
      acertou: false,
      pergunta: "Classifique o Gráfico a seguir",
      imagem: require("../../assets/9.png"),
      tipo: "múltipla escolha",
      nivel_dificuldade: "médio",
      respostas: [
        { id: "a", texto: "O gráfico é crescente.", correta: false },
        { id: "b", texto: "O gráfico é decrescente.", correta: false },
        { id: "c", texto: "O gráfico é constante.", correta: false },
        { id: "d", texto: "O gráfico é uma parábola.", correta: false },
      ],
    },
    { 
      id: 10,
      feito: false,
      acertou: false,
      pergunta: "Classifique o Gráfico a seguir",
      imagem: require("../../assets/10.png"),
      tipo: "múltipla escolha",
      nivel_dificuldade: "médio",
      respostas: [
        { id: "a", texto: "O gráfico é crescente.", correta: false },
        { id: "b", texto: "O gráfico é decrescente.", correta: false },
        { id: "c", texto: "O gráfico é constante.", correta: false },
        { id: "d", texto: "O gráfico é uma parábola.", correta: false },
      ],
    },
  ];
}


export function getVideoAulas() {
  return [
    {
      id: 1,
      titulo: 'Aula sobre Função de 1°Grau!',
      videoId: 'HaPVT_wkUyk',
      exercicio: 1,
    },
    {
      id: 2,
      titulo:'Aula Sobre Gráfico!',
      videoId: 'Ueqv0bkOjEA',
      exercicio:2,
    },
    {
      id: 3,
      titulo: 'Introdução',
      videoId: '6UFBHjArR5o',
      exercicio:'none',
    },

    
  ];
}


